### ISSUE TITLE
fatal error: ns3/antenna-module.h: No such file or directory

### ISSUE THREAD

**Issue by mjk22071998** [tkn-tub/ns3-gym#41]
After running the command `./build.py --enable-examples --enable-tests` on Kali Linux I am getting the error
`
[2253/2895] Compiling build/src/antenna/bindings/ns3module.cc
In file included from src/antenna/bindings/ns3module.cc:1:
src/antenna/bindings/ns3module.h:41:10: fatal error: ns3/antenna-module.h: No such file or directory
   41 | #include "ns3/antenna-module.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Waf: Leaving directory `/home/pentester/ns3 simulator/ns-allinone-3.33/ns-3.33/build'
Build failed
 -> task in 'ns3module_antenna' failed with exit status 1 (run with -v to display more information)
Traceback (most recent call last):
  File "./build.py", line 175, in <module>
    sys.exit(main(sys.argv))
  File "./build.py", line 166, in main
    build_ns3(config, build_examples, build_tests, args, build_options)
  File "./build.py", line 86, in build_ns3
    run_command([sys.executable, "waf", "build"] + build_options)
  File "/home/pentester/ns3 simulator/ns-allinone-3.33/util.py", line 25, in run_command
    raise CommandError("Command %r exited with code %i" % (argv, retval))
util.CommandError: Command ['/usr/bin/python3', 'waf', 'build'] exited with code 1
`

**Comment by talhaibnaziz** [comment]
I am getting the same error for Ubuntu 18.04 when installing with "./waf".

**Comment by Edward2k** [comment]
Same for me

**Comment by lcharles123** [comment]
Same for me, ./build.py  without args on Linux Mint 20 (Ubuntu Focal)

**Comment by Rama3017Krishna** [comment]
Yeah, Same for me but I am getting 
fatal error: ns3/core-module.h: No such file or directory when trying to compile a ns-3 file.
